### ISSUE TITLE
ceilings and floor

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#170]
It seems this isn't working, during lineup print I still see the same fantasy points i entered

**Comment by BenikaH** [comment]
Can you elaborate a bit more? I have already implemented this in my codebase and seems to be working great.

**Comment by Denwen12** [comment]
if I leave the players list with  0 for fppg it still shows 0 for when the lineups are printed even tho I added there ceiling and floor

**Comment by BenikaH** [comment]
I guess it also depends on how you use the ceiling and floor values.

**Comment by Denwen12** [comment]
#
![Screenshot_20200714-203842_Sheets](https://user-images.githubusercontent.com/54749054/87489879-29219880-c612-11ea-81b1-99e79bb73f28.jpg)

I used that in my players-list  but when I generated lines they still would show 0 for projected points

**Comment by BenikaH** [comment]
Ok, gotcha. So, what I think you're wanting is to replace the fppg with a value between fppg.floor and fppg.ceil as a new fppg. Is that what you're expecting?

**Comment by donlaur** [comment]
If the projection is 0fp, it should use it at zero.  Ceiling and floor shouldn’t change the projection in this case.  I do believe, I hadn’t l used it on this project yet.  It maybe shouldn’t include it in the lineups but it depends on how many players you have included and how many lines.  If the projection is zero exclude it from your player pool.

**Comment by donlaur** [comment]
Are you saying that it should take the floor and the ceiling and do data modeling and change the FP number?  If all the projections are 0 then it most likely sees them as equal.  Try changing the FP for every player and see what happens.  Sorry I’m hoping on this project new and having built and used optos so it’s possible I’m misunderstanding the expected result here.  I though it only did a  solver method on the lines, I don’t believe it should change the projection.

**Comment by BenikaH** [comment]
I just used it and it worked as "I" expected. I wanted to see what @Denwen12 was trying to achieve if I understood correctly.

**Comment by Denwen12** [comment]
yes @BenikaH I thought it would randomly select a fits to use

**Comment by Denwen12** [comment]
@donlaur also yes for your question I thought it would randomly use a projection

**Comment by Denwen12** [comment]
maybe I am misunderstanding what this will.do for the lineups, if anyone can explain

**Comment by BenikaH** [comment]
I went back and checked again. So, it doesn't set the fppg to a number within the range of (floor, ceiling) without some help. 
<img width="806" alt="43 54fppg" src="https://user-images.githubusercontent.com/8481136/87577857-8d3f6d80-c6a1-11ea-855e-6d5288308487.png"> In this image, I'm showing the floor and ceiling set to 35 and 80 for DeAndre Ayton (left), on the right is Ayton's info in the lineups generated and it shows his default of 43.54fppg that day. This is how the function works as is.

With a little help in my code, (I'll post at the end here) I was able to get it to randomize between the floor and ceiling values (sometimes - check images)
<img width="869" alt="65fppg" src="https://user-images.githubusercontent.com/8481136/87578273-2e2e2880-c6a2-11ea-8d9c-cd64f0ab6739.png">
<img width="880" alt="89fppg" src="https://user-images.githubusercontent.com/8481136/87578280-30908280-c6a2-11ea-86d2-e0165b6895aa.png">

@Denwen12 I think you were right to expect that. It may need a few more lines elsewhere in the player script or the optimizer script, not sure at the moment. Tried this with uniform and gauss and the numbers weren't drastically different. 

What I found:
1. If you set randomness to true, it will randomize fppg after each lineup is created.
2. If you set randomness to false, it will not randomize fppg after each lineup and it will keep the randomly chosen number throughout the optimization.

When setting randomness to false I get the results below.
<img width="845" alt="62fppg_no_randomness" src="https://user-images.githubusercontent.com/8481136/87580147-07252600-c6a5-11ea-83ce-d4ba7aa54dfd.png">
<img width="843" alt="62fppg2" src="https://user-images.githubusercontent.com/8481136/87580152-08eee980-c6a5-11ea-958c-8f5216db7531.png">

I grabbed @DimaKudosh's code from the rules.py script, put it in my code and optimized.
` if player.fppg_floor is not None and player.fppg_ceil is not None:
          random_fppg = uniform(player.fppg_floor, player.fppg_ceil)
          player.fppg = round(random_fppg,2)`

Hope that helps @Denwen12.

**Comment by DimaKudosh** [comment]
Random value between ceil and floor is used for optimization with randomness but player's fppg is used for printing lineup

**Comment by Denwen12** [comment]
Thank you for the clarification @BenikaH, I wasnt sure if I was using this correctly, so now I know I have to use randomness

**Comment by Denwen12** [comment]
I am only having one other problem with my code I want to generate my LOL lineups with Star with all possible positions using a 4 stack

**Comment by gborh1** [comment]
@DimaKudosh Perhaps the fppg and projections should be divorced from each other completely? The main reason being when printing lineups, you don't just want to to see the total value of the lineup, but the projections on individual players.  When randomizing a lineup currently, it's hard to see that because each player's fppg displays as static. Am I missing something?

**Comment by BenikaH** [comment]
I haven't used the LOL optimizer, do you have a csv file? I can try on my lunch break.

**Comment by BenikaH** [comment]
We can close this as it pertains to the first issue right?

**Comment by Denwen12** [comment]
yes we can close this but stack issue can be used for any sport that
includes star or mvp

**Comment by Denwen12** [comment]
Were you able to look into that? Sorry to be a pain, lmao

**Comment by BenikaH** [comment]
I made a few tweaks to @DimaKudosh 's code in the qistfile.
`from collections import Counter
from itertools import chain
from pydfs_lineup_optimizer.constants import PlayerRank
from pydfs_lineup_optimizer.stacks import PositionsStack, PlayersGroup, NestedPlayersGroup, OptimizerStack
from pydfs_lineup_optimizer.utils import get_players_grouped_by_teams, list_intersection

class PositionsStackWithStar(PositionsStack):
    def build_stacks(self, players, optimizer):
        players_by_teams = get_players_grouped_by_teams(players, for_teams=self.for_teams)
        all_positions = tuple(set(chain.from_iterable(self.positions)))
        positions_for_optimizer = Counter(self.positions)
        positions_for_optimizer[all_positions] = len(self.positions)
        all_groups = []
        for team_name, team_players in players_by_teams.items():
            groups = []
            groups.append(PlayersGroup(
                players=[player for player in team_players if
                         player.rank == PlayerRank.STAR],
                min_from_group=1,
            ))
            for positions, total in positions_for_optimizer.items():
                groups.append(PlayersGroup(
                    players=[player for player in team_players if
                             list_intersection(player.positions, positions) and
                             player.rank == PlayerRank.REGULAR],
                    min_from_group=total,
                ))
            nested_group = NestedPlayersGroup(
                groups=groups,
                max_exposure=self.max_exposure_per_team.get(team_name, self.max_exposure),
            )
            all_groups.append(nested_group)
        return [OptimizerStack(groups=all_groups)]
    
class TeamStackWithStar(TeamStack):
    def build_stacks(self, players, optimizer):
        players_by_teams = get_players_grouped_by_teams(players, for_teams=self.for_teams)
        all_teams = tuple(set(chain.from_iterable(self.for_teams)))
        teams_for_optimizer = Counter(self.for_teams)
        teams_for_optimizer[all_teams] = len(self.for_teams)
        all_groups = []
        for team_name, team_players in players_by_teams.items():
            groups = []
            groups.append(PlayersGroup(
                players=[player for player in team_players if
                         player.rank == PlayerRank.STAR],
                min_from_group=1,
            ))
            groups.append(PlayersGroup(
                players=[player for player in team_players if team_name in self.for_teams],
            min_from_group=self.size))

            nested_group = NestedPlayersGroup(
                groups=groups,
                max_exposure=self.max_exposure_per_team.get(team_name, self.max_exposure),
            )
            all_groups.append(nested_group)
        return [OptimizerStack(groups=all_groups)]

--------------------Positions Stack-----------------------------
optimizer = get_optimizer(Site.FANDUEL, Sport.LEAGUE_OF_LEGENDS)
optimizer.load_players_from_csv('/Users/players-list.csv')
optimizer.add_stack(PositionsStackWithStar(['TOP', 'S,'MID','TEAM'], for_teams=['SB']))
lineups = list(optimizer.optimize(n=5))
for lineup in lineups:
    print(lineup)

------------------------TeamStack--------------------------------
optimizer = get_optimizer(Site.FANDUEL, Sport.LEAGUE_OF_LEGENDS)
optimizer.load_players_from_csv('/Users/players-list.csv')
optimizer.add_stack(TeamStackWithStar(4,for_teams=['SB']))
lineups = list(optimizer.optimize(n=5))
for lineup in lineups:
    print(lineup)`


The first function like Dima has, you should specify positions, the second, just choose size and team(s).
