### ISSUE TITLE
Player Exposure

### ISSUE THREAD

**Issue by holmes72** [DimaKudosh/pydfs-lineup-optimizer#174]
Is there a way to print the player exposure count?  That is, the number of times a player is used in all generated lines.  Would be nice to see this for all players even if the count is 0, sorted by descending count.

**Comment by DimaKudosh** [comment]
In the new version you can call `print_statistic` method after optimization

**Comment by holmes72** [comment]
I installed earlier this week, so I assume I have the new version.  But I can't find this method so perhaps I don't have the new version.  Can you give an example of calling this method?

**Comment by DimaKudosh** [comment]
I released the new version on weekends, the latest version is 3.3.0 if you have this version you can call this command after optimization:
```
optimizer.optimize(10)
optimizer.print_statistic()
```

**Comment by holmes72** [comment]
I uninstalled 3.2.0 and installed 3.3.0, and I'm still getting error:
'LineupOptimizer' object has no attribute 'print_statistic'

I'm not seeing any method like "statistic" in the lineupoptimizer object (or the project for that matter).  What am I missing?

**Comment by DimaKudosh** [comment]
It's strange, are you sure that you installed 3.3.0? Can you run:
```
from pydfs_lineup_optimizer import __version__
print(__version__)
```

**Comment by holmes72** [comment]
Yep...3.2.  I got it upgraded and the method works as advertised.  Thanks!
